---
sudo: false
language: ruby
cache: bundler
bundler_args: --without system_tests
before_install: rm Gemfile.lock || true
script: bundle exec rake validate lint spec 
matrix:
  fast_finish: true
  include:
    - rvm: 2.1.9
      env: PUPPET_GEM_VERSION='~> 4.0' COVERAGE=yes
    - rvm: 2.4.4
      env: PUPPET_GEM_VERSION='~> 5.0' COVERAGE=yes
notifications:
  email: false
